### ISSUE TITLE
Only folders?

### ISSUE THREAD

**Issue by fakefarm** [itod/pathological-docs#1]
Hello,
Just got a new app and doing my usual download of Fluid and noticed this [other app of yours](http://celestialteapot.com/pathological/). Looks really interesting! I spent 2m or so looking at the docs and examples to try to see if the search queries also returns specific files or just directories like your image shows? I also poked around your docs to see if there were some example searches to get me warmed up to the query language. Any suggestions for _Top 10_ query examples to get me going?

Also, would you consider `path` a compliment or competitor to Alfred?

Thanks!
Dave

![](http://celestialteapot.com/pathological/i/pathological_screenshot.png)
_Wondering if searches can return more than directories_

**Comment by itod** [comment]
Hi Dave, as stated in the docs, there are two `node` types: `file` and `folder`. There are other types as well (`boolean`, `number`, `string`, `date`). Pathological has a free trial available: http://celestialteapot.com/pathological/

Give it a shot with a query like `~/Desktop/*` to see it return some files.

**Comment by fakefarm** [comment]
Ah. Sorry I missed that. Thanks for the clarification. I'll give it a shot!
